export const ROLE_TYPES = [
  "Backend Development",
  "Business Intelligence",
  "Cloud Engineering",
  "Data Engineering",
  "Data Science",
  "DevOps/Infrastructure",
  "Embedded Systems",
  "Frontend Development",
  "Full Stack Development",
  "IT Support",
  "Machine Learning",
  "Mobile Development",
  "Product Management",
  "QA/Testing",
  "Research",
  "Security Engineering",
  "Software Engineering",
  "Systems Engineering",
  "Technical Writing",
  "UX/UI Design",
] as const satisfies readonly string[]

export const INDUSTRIES = [
  "Agriculture",
  "Automotive",
  "Biotech/Pharma",
  "Consulting",
  "Cybersecurity",
  "Defense/Aerospace",
  "E-Commerce/Retail",
  "Education",
  "Energy",
  "Finance/Banking",
  "Government",
  "Healthcare",
  "Insurance",
  "Manufacturing",
  "Media/Entertainment",
  "Non-Profit",
  "Real Estate",
  "Technology",
  "Telecommunications",
  "Transportation/Logistics",
] as const satisfies readonly string[]
